### ISSUE TITLE
Avoid use of `setup.py (anything)`

### ISSUE THREAD

**Issue by jaraco** [tox-dev/tox#1100]
In [this comment](https://github.com/tox-dev/tox/issues/809#issuecomment-443436586), I describe an issue where tox invokes `setup.py --name` (not sure why exactly).

As the Python Packaging ecosystem is seeking to discourage use of distutils and setuptools, and as PEP 517/518 provides a mechanism for other build systems to be in place, other projects like tox should seek to find replacements that avoid the invocation of setup.py and the issues that arise from using it.

In pypa/packaging-problems#224, I've begun the process of specifying what will be necessary to actually support this use-case (and similar). I'm creating this issue as a placeholder but also to investigate why `setup.py --name` is used and if it could possibly be replaced by something else before proper support for unbuilt package metadata is available.

**Comment by gaborbernat** [comment]
Note this probably is something that should be done only when isolated build is turned on. Otherwise for backwards compatibility we do need to support features. Now we need to investigate where we do use it pep 517 provides alternatives. If not I'm afraid to not loose features we probably need to conditionally enable this calls when the backend is setuptools. Definitely though something we need to investigate and address.

**Comment by Aareon** [comment]
Or simply allow both methods. Old setup.py should be left, as well as maintained, but I believe providing the new packaging standards is a good idea.

**Comment by gaborbernat** [comment]
Done with tox 4.
