### ISSUE TITLE
Consider `tox.ini` to be frozen?

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#1123]
As mentioned in several places already I would like to declare the old `tox.ini` format as "done" and all future changes should be considered for the upcoming `pyproject.toml` based format discussed in #999.

The old format as it is should be documented completely (I started collecting the missing parts that were never documented properly at the moment) and then declared feature complete. 

Bugs can and should still be fixed with the caveat that it might be hard to decide nowadays what a bug and what a feature is in that format :laughing:

**Comment by gaborbernat** [comment]
Well I would consider doing this only after we're finished with a feature parity toml configuration format. No need to rush ahead and freeze something before we can point to a better alternative.

**Comment by obestwalter** [comment]
> Well I would consider doing this only after we're finished with a feature parity toml configuration format. 

You could also argue from the position that the existing format is "good enough" inependent of an alternative. It might seem strange in the realms of software but things can be just done sometimes and don't need eternal expansion and improvement :)

For the existing tox config I feel that way because there are to many things you can't fix properly anymore anyway, because they grew like they did and people rely on that behaviour (may it be documented or not). See #1121 and #1113 for recent examples.

So we do not necessarily have to have something better to point to, when what we have is good enough for 90% of the users. Deciding not to work on these topics in the old format would also free up time to work on the new one.

**Comment by gaborbernat** [comment]
@obestwalter I think the difference is that I'm not convinced what we would come up would be any better. I view that more as an experiment, rather than definitive go-ahead direction. Once the experiment becomes successful we can decide to drop the old one. However, we might conclude that what we have at the moment is still the best, in which case we may just continue on with it. I know the ini is not perfect, but from my experience, the toml also has its drawbacks. I would be reluctant to stop the progress of either of those. Let's instead leave people to decide what they like rather than us enforcing it. Furthermore, if the new format will require us breaking all existing plugins (e.g. #1121 definitely would make it so), I'm personally not a big fan of it. It would basically take us back five year to the time where tox plugins were not a thing until plugin developers migrate (which could be a long time).

**Comment by gaborbernat** [comment]
I think until we prove an alternative to be at least as powerful we don't need to consider this, so I'll close it for now.
