### ISSUE TITLE
Improve hook system

### ISSUE THREAD

**Issue by ionelmc** [tox-dev/tox#1131]
So I'm trying to implement a wheel plugin and there are some problems:
- ~I want to add some ini options from within a plugin however it's sort of impossible without copypasting copious amounts of code from tox.~
- I need to monkeypatch `tox.package.build_package`
- No good place to support wheels when tox is in isolated mode (when using pyproject.toml for building)
- No nice way to have an error when something ain't found in the venv (another monkeypatch)

I would like to discuss these probably bad ideas:

- ~`tox_configure(config, reader, content)` - would probably need to refactor that ParseIni class into a module, it doesn't make sense to be a class anyway, cause the instance is always thrown away. (`reader` would be the `[tox]` SectionReader, `content` would be the raw file parser)~ (nvm, I didn't find `add_testenv_attribute` initially)
- `tox_build_package(config, report, venv, session)` 
- `tox_perform_isolated_build(build_info, package_venv, venv, session, config, report)` 

Also, the wheel plugin is here: https://github.com/ionelmc/tox-wheel/blob/master/src/tox_wheel/plugin.py

**Comment by ionelmc** [comment]
Actually, about the isolated builds, it would be nicer for that feature to be completely invisible to the user by default. Eg: if there's a pyproject.toml activate isolated builds automatically.

Also, can't something external be used to do the building, something that supports pyproject.toml but can build inplace without copying stuff to a tmpdir like pip?

**Comment by gaborbernat** [comment]
> `tox_configure(config, reader, content)` - would probably need to refactor that ParseIni class into a module, it doesn't make sense to be a class anyway, cause the instance is always thrown away. (`reader` would be the `[tox]` SectionReader, `content` would be the raw file parser)

First and foremost we'll load all configuration specified inside the reader. So in theory as long as users specify a key x inside the ``tox.ini``, you'll have it available. You will not have the option to validate it though, however, you can do this inside https://github.com/tox-dev/tox/blob/master/src/tox/hookspecs.py#L13. Going ahead, yes we should separate ini parsing and config validation, and add hooks for plugins to register configurations for them.

> `tox_build_package(config, report, venv, session)` 

- The reason why we don't have this is because the logic here (https://github.com/tox-dev/tox/blob/master/src/tox/package/__init__.py#L10) would be different for a wheel. In case of wheel you no longer can reuse the wheel built beforehand, and you need to potentially build one per environment (unless you have universal wheels - but even to find this out you would need to look in multiple places e.g. flit, setuptools, poetry may store this flag in different places). In general detecting when you need to build one wheel or more than one can be a hard problem to solve (note must be general for all builders). If you only want to solve ``tox-wheel-setuptools`` then this could simplify things (you probably just need to parse the ``setup.cfg`` in this case), however note ``tox`` aims to support all PEP-517 compliant builders. Again this is one of the reasons why we haven't implemented this yet. As you see there's a lot of subtle cases to solve.

> `tox_perform_isolated_build(build_info, package_venv, venv, session, config, report)` 

What would this actually do? Why would we want to expose it as a plugin?

> Also, the wheel plugin is here: https://github.com/ionelmc/tox-wheel/blob/master/src/tox_wheel/plugin.py

Looking at your code a few things (your implementation seems to be the old wheel build logic, setuptools only). You would need to use https://www.python.org/dev/peps/pep-0517/#build-wheel in order to support general build. Furthermore, you don't install build dependencies (furthermore build dependencies should not affect the test env, so you probably can't reuse the passed in ``venv`` to build). Your plugin seems more pre PEP-517, rather than PEP-517.

> Actually, about the isolated builds, it would be nicer for that feature to be completely invisible to the user by default. Eg: if there's a pyproject.toml activate isolated builds automatically.

The reason why we don't automatically enable isolated build is because it would be backwards incompatible change (with tox 4 we might make it the default), and plus it cannot be automatically enabled in all cases as the ``pyproject.toml`` needs to specify correctly both the ``build_requires`` and the ```build_backend``.

> Also, can't something external be used to do the building, something that supports pyproject.toml but can build inplace without copying stuff to a tmpdir like pip?

Not really. Hence why we have our own little PEP-517 implementation. We could use https://github.com/pypa/pep517 (pip also uses that), however did not want to pull in all that code yet given we have most of it already implemented in ``venv.py``. Going ahead in long term we'll probably try to have a ``pip build sdist`` and ``pip build wheel`` command in pip, and we'll delegate to those. Performance and edge cases still need to be validated though (e.g. when it's not good to use pip build).

**Comment by ionelmc** [comment]
So about the conflicts, lets say I have this these configurations:

A. `[testenv:py27] deps = foobar==1.1` and either `[build-system] requires = foobar>=1.0` or  `[testenv:py27-builder] deps = foobar>=1.0`
B. `[testenv:py27] deps = foobar==1.0` and either `[build-system] requires = foobar>=1.1` or  `[testenv:py27-builder] deps = foobar>=1.1`

Can't easily merge the deps for neither A or B cause pip don't allow doubly specifying a dep.

So then we run the install command two times. All is fine but B should be an error situation - there is ambiguity which users won't notice and tests will not always perform as expected.

The argument that you can't test that the compiled code works without cython is fair, but I'd like a solution that also makes the problem in B an error.

**Comment by ionelmc** [comment]
Errr .. so the ambiguity in B is that foobar is upgraded to 1.1 but the user asked for 1.0 in `tox.ini`. Can't argue that the same user asked for 1.1 - imagine that foobar is a sub-sub-sub build dependency.

**Comment by gaborbernat** [comment]
@ionelmc First, I've been thinking about this and came to the conclusion that ``99.99%`` of the time the builder environment should not have any dependencies. I'm thinking of disallowing deps like that and instead only allowing ``requires``. 

So this simplifies conflicts with ``build-requires`` and ``testenv``. 

I find those two different goals though. ``build-requires`` are build dependencies and need to be satisfied in the build env only, similarly ``testenv`` dependencies are ``install requires`` only and need to be satisfied in the test environment only. Given this separation, I don't think there is any conflict here. Am I missing here something?

**Comment by ionelmc** [comment]
Hmmmmm ok so I have learned some things now. I would like to move the discussion in the tox-wheel repo.
