### ISSUE TITLE
Allow tox runs for existing virtualenvs without internet access

### ISSUE THREAD

**Issue by sigmavirus24** [tox-dev/tox#1151]
Hi all,

Often times, I find myself travelling for a conference or work and wanting to get things done on an airplane without paying ridiculous sums of money for terrible internet. I leverage `tox` in many F/OSS projects ([github3.py][], [rush][], [uritemplate][], [urllib3][]). The problem occurs if I have recently created virtualenvs but run `tox` then it tries to force pip to check PyPI and since there's no internet I can not use tox to run my tests, instead I have to do `.tox/py37/bin/pytest` and reproduce the commands in my tox.ini.

It would be excellent if it were possible to run `tox` without having to always hit the internet. (For what it's worth pip can install from the cache locally.)

[github3.py]: /sigmavirus24/github3.py
[rush]: /sigmavirus24/rush
[uritemplate]: /python-hyper/uritemplate
[urllib3]: /urllib3/urllib3

**Comment by gaborbernat** [comment]
As long as pip hits the cache locally and you do set the no download flag for virtualenv (can be set via an environment variable) this should work just fine. tox itself never tries to reach out to the internet itself, only via pip. 

Myself I run on my Dev machine a devpi server and point my pip index URL via environment variable towards that whenever I'm on a plane (or generally otherwise).

**Comment by sigmavirus24** [comment]
Would it be unreasonable to have a flag in tox to inject that environment variable?

**Comment by gaborbernat** [comment]
It would not be unreasonable, though one could argue it would increase our API width. Arguably you would want this to be always on though, not? In this case just add to the tox.ini:

```ini
[testenv]
setenv = VIRTUALENV_DOWNLOAD=0
         PIP_DISABLE_PIP_VERSION_CHECK=1
```

Note I also often disable pips version check logic.
