### ISSUE TITLE
integration tests for core libraries

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#1158]
With trying to improve the code base and move away from long source files we tend to break some of our plugins. Similar to https://github.com/pypa/integration-test we should also periodically run the master against some popular tools and ensure these don't break before doing a new release.

**Comment by gaborbernat** [comment]
Created https://github.com/tox-dev/integration-test for this scope.

**Comment by gaborbernat** [comment]
This now has been done under https://github.com/tox-dev/integration-test, as start added Linux python3.7 run for tox-travis and tox-pipenv. Created the test repo in a way to allow setting up the tests locally and allowing modifying the GitHub repositories (option to fix bugs in-place). Also allows running the tests against a custom branch from here.

I wanted to add `tox-venv` too but the CI for that fails ATM on master, @asottile any ideas?

@obestwalter @asottile What other tox plugins are popular enough to worth adding?

**Comment by asottile** [comment]
hmm yeah the tests have been failing on tox-venv for a while it seems -- looks like @rpkilby is fixing them: https://github.com/tox-dev/tox-venv/pulls

**Comment by gaborbernat** [comment]
Feels like that project has a lot of tests considering how little it actually does 🤔

**Comment by asottile** [comment]
It has a vendored copy of the tox testsuite iirc

**Comment by rpkilby** [comment]
> looks like @rpkilby is fixing them: https://github.com/tox-dev/tox-venv/pulls

I'm low on bandwidth at the moment, and tox-venv is close to the bottom of my list. I imagine it will be several months before I'm able to really get around to looking at it.

> Feels like that project has a lot of tests considering how little it actually does 🤔

Yes and no. `tox-venv` is just swapping out `virtualenv` for Python 3's builtin `venv`. Since this change is just an internal implementation detail, there is no new user-facing functionality to actually test. However, it is important to ensure that `tox-venv` doesn't change the existing functionality, which is why I've vendored a copy of tox's test suite. i.e., if `tox`+`tox-venv` passes a (very slightly modified) copy of the test suite, then we should be good to go.

The problem is that keeping the test suite up-to-date has been an absolute pain. `tox-venv` is not only pinned to a specific version of tox's test suite, but the entire runtime/test environment. iirc, there were some changes to pytest that changed output, which is what's causing the breaking changes. I don't exactly remember, as I was looking into this back in September.

**Comment by gaborbernat** [comment]
I wonder though, now that virtualenv is maintained any reason to swap out virtualenv with venv?

**Comment by rpkilby** [comment]
> It has a vendored copy of the tox testsuite iirc

Just to clarify, this is correct with the exception that there are some minor output changes to the test. e.g., 
- https://github.com/tox-dev/tox-venv/pull/26/commits/38ed76f6bd39f25b08d75ce04c20ceabfc84c633 updates the test suite to the (at the time) latest version 
- https://github.com/tox-dev/tox-venv/pull/26/commits/ea0c0f7b28b504761d590a13b2a70abf66825401 reapplies the tox-venv changes to the test suite.

**Comment by rpkilby** [comment]
> I wonder though, now that virtualenv is maintained any reason to swap out virtualenv with venv?

Hm. My view on this is kind of the opposite. Given that venv largely has feature parity[*] with virtualenv, and given that Python 2 is EOL in less than a year, I'm not sure what benefit virtualenv provides moving forward. i.e., why should tox use virtualenv instead of the builtin venv module? Does it provide enough benefit to require it as a dependency? 

I don't mean to dismiss virtualenv or anything - it obviously played an important role in Python's packaging history - but shouldn't virtualenv be retired? Is there something that I'm missing?

[*] The exception being some more obscure features not used by tox (e.g., relocatable) and the `-p <python interpreter>` argument, which I don't think is really necessary due to `venv` being part of the standard library. e.g., why would do `python3.7 -m venv -p python3.6` when you could just do `python3.6 -m venv`?

**Comment by asottile** [comment]
at least for me, `virtualenv` is a much more portable solution.  `debian` (and probably others) don't ship `python3-venv` (which contains ensurepip + venv modules) by default

**Comment by rpkilby** [comment]
How do you install `virtualenv`/`tox` to your system then?

**Comment by asottile** [comment]
I don't, I `curl https://asottile.github.io/get-virtualenv.py | python3 - ~/opt/venv` and symlink things into ~/bin

(soon this will be on bootstrap.pypa.io but I haven't finished the pypa parts yet). I manage that virtualenv in https://github.com/asottile/personal-puppet

I don't touch the system site packages at all

**Comment by rpkilby** [comment]
> I don't touch the system site packages at all

I should have been more specific - didn't mean a system-wide install. Just generally meant "how do you make virtualenv available at a user level?".

Either way, I guess it makes sense to continue using virtualenv by default. As mentioned, not all systems will have venv, and `virtualenv` is at least pip-installable once you're in some kind of virtual environment. Maybe in some future where venv is always built into Python, `venv` could be the default..

> I wonder though, now that virtualenv is maintained any reason to swap out virtualenv with venv?

In my cases, where I *know* `venv` exists on the target machine, I still prefer to use the builtin `venv`. It's just one less dependency, one less thing to rely on.

**Comment by gaborbernat** [comment]
In practice though virtualenv has more features than venv though so might be desirable over venv in some cases. If you managed to acquire tox any sane installer will pull in virtualenv, so not sure if it's a true extra dependency to worrie about I believe.

**Comment by rpkilby** [comment]
> In practice though virtualenv has more features than venv

Sure, but as far as I'm aware, tox doesn't take advantage of these features. Aside from the installation issue, `virtualenv` could be functionally swapped out for `venv`, right?

> If you managed to acquire tox any sane installer will pull in virtualenv, so not sure if it's a true extra dependency to worrie about I believe.

I mean a runtime dependency instead of an installation dependency. e.g., `virtualenv` had past issues with it's `site.py` module that, when ran with the `-Werror` option, would cause tox to fail. Given that `venv` doesn't need to support multiple versions of Python, it is less of a liability in that sense.

----

Either way, the installation issue is important enough to warrant continued use of `virtualenv`.
