### ISSUE TITLE
Misleading documentation about using version constraints

### ISSUE THREAD

**Issue by mgedmin** [tox-dev/tox#1167]
https://tox.readthedocs.io/en/latest/example/basic.html#depending-on-requirements-txt-or-defining-constraints suggests adding `-cconstraints.txt` to `deps` if you want to define version constraints, but  this doesn't actually affect any dependencies defined in your setup.py's `install_requires`.

AFAICS the only way to affect those is to redefine `install_command`:

```
[testenv]
install_command = python -m pip install {opts} -c constraints.txt {packages}
```

I suggest updating the docs to mention that.

**Comment by apljungquist** [comment]
First, I agree the documentation is misleading.

Second, for anyone stumbling across this thread when trying to solve this problem for themselves; patching the install command does not work when constraints.txt contains hashes because [pip will refuse to install any package without a hash](https://pip.pypa.io/en/stable/user_guide/#hash-checking-mode) and the hash of the package under test is not known in advance.

Unfortunately , I know of no clean method of pinning the dependency versions in a testenv. My best candidate so far is to add `-cconstraints.txt -rrequirements/install_requires.txt` to `deps`, and to refactor the project such that dependencies are all listed in that file.

**Comment by graingert** [comment]
`pipx run dephell convert -- --from=pyproject.toml --to=requirements.lock` will generate a constraints file for all package `[extras]`

then this will work
```
[testenv]
install_command = python -m pip install {opts} -crequirements.lock {packages}
```

however tox needs to pass the `--hash=sha256:` of the package

**Comment by apljungquist** [comment]
@graingert do you have a method of convincing tox to provide the checkusm?

I have been toying with a [plugin](https://github.com/apljungquist/tox-constraints), but it flawed to say the least. In particular it does not pin packages in the isolated build environment `.package`. Now I am investigating using the `tox_package` hook to create temporary constraints files and patch the install command.

pip accepting wildcard hashes for local packages sure would make life easier...

**Comment by gaborbernat** [comment]
This is now documented under https://tox.readthedocs.io/en/rewrite/faq.html#using-constraint-files

**Comment by graingert** [comment]
> This is now documented under https://tox.readthedocs.io/en/rewrite/faq.html#using-constraint-files

Does this now work with hashed constraints?

**Comment by graingert** [comment]
> @graingert do you have a method of convincing tox to provide the checkusm?


Yes! I made a custom install command and it generates a requirements.txt on the fly

https://github.com/PyCQA/modernize/pull/228/files#diff-538613b9b6f5becd9e4ed4ff74271a857d0d77122d017a170f092195c7e326e5R79

**Comment by jugmac00** [comment]
@graingert Could you create a PR and add a note about that?

**Comment by gaborbernat** [comment]
> Does this now work with hashed constraints?

It should, if not it's a bug.

**Comment by gaborbernat** [comment]
Can you clarify what do you mean?
