### ISSUE TITLE
develop mode broken with pip 19.1

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#1276]
due to https://github.com/pypa/pip/pull/6370 (follow up discussion on https://github.com/pypa/pip/issues/6434)

**Comment by tom-dalton-fanduel** [comment]
Here's the details for my case:

**Environment**

* pip version: 19.1
* Python version: 3.6
* OS: Linux

**Description**

`pip install` fails with a requirements file that references a setup.py file, in a project that has a pyproject.toml file that has no build tooling section.

My project setup:

```
setup.py  # Contains the actual project/package requirements
pyproject.toml  # Contains only 2 lines of black configuration
requirements/base.txt  # Contains only `-e .`
requirements/testing.txt  # Contains `-r base.txt` and then other stuff like pytest etc.
```

This setup allows us to:
* Specify the project requirements exactly once (in the setup.py)
* Use a command like `pip install -r requirements/testing.txt` to install both the project requirements along with other stuff needed to run the tests.
* Build the package with `python setup.py sdist`

The suggested workaround in https://github.com/pypa/pip/pull/6370#issuecomment-486153504 doesn't seem to work for me:

```
pip install --no-use-pep517 -q --upgrade --requirement /..../src/requirements/development.txt
ERROR: Error installing 'file:///.... (from -r /..../src/requirements/_base.txt (line 1))': editable mode is not supported for pyproject.toml-style projects. pip is processing this project as pyproject.toml-style because it has a pyproject.toml file. Since the project has a setup.py and the pyproject.toml has no "build-backend" key for the "build_system" value, you may pass --no-use-pep517 to opt out of pyproject.toml-style processing. See PEP 517 for details on pyproject.toml-style projects.
```

`pip install -r requirements/testing.txt` fails 

**Expected behavior**

Historically (in <= 19.0.3) pip would install the project and testing/dev requirements (into the current virtualenv).

**How to Reproduce**

Set up a project as per above, try to install the dev/testing requirements with `pip install -r foo.txt`.

**Output**

As per description.

**Comment by tom-dalton-fanduel** [comment]
Relevent issues:

https://github.com/pypa/pip/issues/6375
https://github.com/pypa/pip/issues/6314
https://github.com/pypa/pip/pull/6370

**Comment by gaborbernat** [comment]
@tom-dalton-fanduel I think you wanted to comment under the pip issue tracker, not here 👍 This is a downstream break, your issue and reproduce is for upstream pip.

**Comment by cjerdonek** [comment]
Have you tried putting the option inside your requirements file?

**Comment by tom-dalton-fanduel** [comment]
:man_facepalming: Sorry! Will move all the above to a new puip issue!

**Comment by webknjaz** [comment]
Oh.. I was about to suggest `--no-build-isolation` in this case but isolated env on tox level with installing `requires` from `pyproject.toml` there...

**Comment by webknjaz** [comment]
Workarounds:
* https://github.com/ansible/molecule/pull/2009/files
* https://github.com/jaraco/skeleton/commit/123b0b2

**Comment by gaborbernat** [comment]
Per upstream discussion pip will fix this on their side.
