### ISSUE TITLE
Environment without envdir

### ISSUE THREAD

**Issue by goerz** [tox-dev/tox#1488]
Is there any way to define a tox environment that does not create an `envdir`, but *only* runs an external command (in `whitelist_externals`)?

One example that I have in mind is a `clean` environment so that `tox -e clean` would clean all built/testing artifacts, including the `.tox` directory itself. At least on Windows, deleting `.tox` while there are still open files inside of it is not possible.

I did come across https://github.com/obestwalter/tox-direct that looks like it's going in the right direction. Is there any other (cleaner/built-in) way to have `tox` "just run a command" without creating an `envdir` in `.tox` (or even touching the `.tox` directory at all)?

Are there any good alternatives to cleaning? I do like to include a `Makefile` that has `make clean`, but that's rather unix-specific, and I was hoping to have `tox` by itself as a platform-independent solution for *all* dev-related tasks.

**Comment by gaborbernat** [comment]
By definition what you're proposing is not supported out of box for good reasons. You might use tox-direct to sidestep things, but need to emphasize again that's not supported by tox itself🤷‍♂️ if you want clean use shutil.rmtree and create the python environment for it. That's the only paths supported by core.

**Comment by BenjamenMeyer** [comment]
`At least on Windows, deleting .tox while there are still open files inside of it is not possible.`
That's by design due to Kernel Locks on the files as Windows uses a non-shareable read/write mode by default; these kernel locks can often lead to the need for reboots when things crash or shutdown incorrectly.

If you use Makefiles, just make sure they're compatible across various versions of make. A simple one for `make clean` should be able to function under both GNU Make and Microsoft's nmake which should support cross-platform needs.
