### ISSUE TITLE
Allow environment creation but don't run the tox.ini commands on it

### ISSUE THREAD

**Issue by namasher** [tox-dev/tox#1530]
Hi, I think a really cool feature about tox would be to be able to create virtualenvs with the requirements/local packages of a environment located in tox.ini. This would allow to use this virtualenv later on to run custom commands or using tox.ini commands. 

The use case is: I need to create a virtualenv and then some time later run some pytest tests on it. The only alternative I currently have is to create the virtualenv and pass a name of a test that does not exists(telling pytest to ignore errors) so the virtualenv gets created and later on pass the true test names.

**Comment by skrech** [comment]
Hello,
I was searching for the same feature, but with different use-case in mind.
I use docker to run my micro-services. I decided for the tests to also be run in the containers so they are isolated from the current dev env or platform. However:

1. When I use "docker run ..." to start the tests, virtualenvs are recreated every time before running tests because "run" command start new containers.
2. If I put tox virtualenv creation in the Dockerfile I have to run  the tests every time the image is build.

It will be great if there is a command similar to:
`tox --env-only`
That will only create the virtual environments. It would be then possible to put it in a ONBUILD directive in a Dockerfile.

**Comment by asottile** [comment]
I believe you're looking for the `--notest` argument

**Comment by asottile** [comment]
or, what might be better suited for your uses, `tox --devenv DIR`

**Comment by skrech** [comment]
> I believe you're looking for the `--notest` argument

That's exactly what I needed. Thanks!
However, maybe it's a good idea to put an example in the Tips section of the documentation so this option is easily discoverable. I think this is very valuable for every kind of scenarios that incorporates any form of CI or containerized environment.

**Comment by asottile** [comment]
feel free to send a patch!
