### ISSUE TITLE
Migration from sdist to setuptools and isolated_build

### ISSUE THREAD

**Issue by eine** [tox-dev/tox#1650]
Coming from https://github.com/actions/virtual-environments/issues/1381#issuecomment-671360917, I tried adding a `pyproject.toml` file (as explained in https://tox.readthedocs.io/en/latest/example/package.html): https://github.com/eine/vunit/commit/9ec4f36a7fcfa6589d64bdad1ce132cd39eb4821. However, the `setup.py` in VUnit/vunit imports some internal functions (https://github.com/VUnit/vunit/blob/master/setup.py#L14-L15). As a result, tox fails to install the package: https://github.com/eine/vunit/runs/967368728?check_suite_focus=true#step:5:23. What is the recommended approach in this case?

**Comment by gaborbernat** [comment]
The build backend has no responsibility to include the source tree onto the sys.path, so if you're realying on this behaviour you should do this explicitly in setup.py.

If you're backend is in-source tree follow https://www.python.org/dev/peps/pep-0517/#id18, or otherwise just alter sys path as setup.py loads, see https://github.com/python/mypy/blob/master/setup.py#L13

**Comment by eine** [comment]
@gaborbernat, thanks! I didn't understand the reference to PEP517, but `sys.path.insert(0, str(Path(__file__).parent.resolve()))` worked.
