### ISSUE TITLE
Provide global substitution variable for bin folder name ("Scripts" vs "bin")

### ISSUE THREAD

**Issue by fredrikaverpil** [tox-dev/tox#1662]
I find it very cumbersome to use the [platform](https://tox.readthedocs.io/en/latest/example/platform.html) option, when you just need to make sure a call to another tox venv's binary with cross-platform support.

For example, the following is not cross-platform compatible, because on Windows, the "bin" folder is actually named "Scripts":

```
{toxworkdir}/poetry/bin/poetry --version
```

Can we please have a global substitution variable which will be substituted to the name of the bin folder, depending on the platform Tox is being exectued on?

Example:

```
{toxworkdir}/poetry/{binfoldername}/poetry --version
```

**Comment by gaborbernat** [comment]
> And just to be super clear, when I run my previously posted code block with `tox -e poetry,pytest`, poetry installs all pytest dependencies into the actual `.tox/pytest` venv. Not into some arbitrary virtual environment somewhere else.

At the moment tox is designed to be the one handle dependency installation, not poetry.

> Do you think that tox today could support a plugin which will enable dependencies between tox testenvs,

At the moment tox does not support this behaviour. I'm not saying it's not a valid use case, just that tox is not designed at its core at the moment to do this, and I'm not sure a plugin could achieve this. It's something fundemental that would require a majore rearchitecture at the core of tox.

I'm not sure how much can be done at the moment with what we have... and honestly I don't have the free time to look into it to find out. It's something we could build into the rewrite of tox, https://github.com/tox-dev/tox/tree/rewrite but there's no ETA on that, maybe start of next year. In the meantime, you could try to hack together things with a plugin, and make it work in general case, but will not integrate nicely in the current architecture.

**Comment by mikenerone** [comment]
If someone creates a tox plugin, then rather than try to solve the "have one env use an executable from another" direction, what it should do is simply enable to to read the test dependencies from Poetry's settings in pyproject.toml so tox can handle installation of the test dependencies itself like it always has.

**Comment by mikenerone** [comment]
IMO, the true root limitation here is that there's currently no standardized way for a project to communicate sets of dependencies (of which test dependencies is just one set) to an environment-building system like tox. The de facto "standard" is to call `pip`, so that's the only way tox supports right now, but that means `requirements.txt` files, which is exactly one of the assumptions that modern build systems and PEP 517 itself are trying to get away from.

Since it doesn't seem like such a standard is imminent (PEPs 621 and 508 seem like the most related, but don't fully address the issue, and don't appear to be anywhere close to fruition anyway), it seems to me that it falls to tox to find a way to work more flexibly with PEP 517 systems. Some more flexible syntax is necessary for finding dependency sets. Perhaps something as simple as:

```
deps = <plugin_name>:<arbitrary_string_that_plugin_understands>
```
E.g.
```
deps = poetry:dev-dependencies  # This is the name of the dev deps set within poetry's hierarchy.
```
Backward compatibility can be maintained since pip-style deps wouldn't start with a plugin tag.
