### ISSUE TITLE
environment definition question

### ISSUE THREAD

**Issue by sfc-gh-mkeller** [tox-dev/tox#1873]
I would like to for some clarification. As I understand shouldn't an environment defined as this:
https://github.com/tox-dev/tox/blob/833b33f84c02ee7e142d4fad5fc00f1120a3c1e2/tox.ini#L81
inherit from `testenv` and by extension by `pyNN`?

I've pulled your repo and I'm trying to see why `py36-coverage` is not a valid environment.

Thank you so much for your help and time!

**Comment by gaborbernat** [comment]
All ``testenv:x`` inherits from ``testenv``. ``pyNM`` too inherits from ``testenv``. However ``py36-coverage`` is not defined, hence per see not valid. We only have ``py36`` and ``coverage`` environments defined there. You'd need to define somehow the ``py36-coverage`` first to be valid, or introduce the coverage as factorial rather than direct environment. See https://tox.readthedocs.io/en/latest/config.html#generating-environments-conditional-settings

**Comment by sfc-gh-mkeller** [comment]
Understood, thank you!
