### ISSUE TITLE
[tox4] Registation of a run_env replaces the default one

### ISSUE THREAD

**Issue by frenzymadness** [tox-dev/tox#2264]
If I register my own custom environment by this small piece of code:
```python
@impl
def tox_register_tox_env(register):
    register.add_run_env(CurrentEnv)
```

it becomes the default one even it should not be until I set it explicitly. Config contains this:
```
ipdb> config.options.default_runner
'current-env'
```
A possible workaround is to set the default runner back to the default one:
```python
@impl
def tox_add_core_config(core_conf, config):
    config.options.default_runner = 'virtualenv'
```

**Comment by gaborbernat** [comment]
Ah, this is because the order of execution for pluggy plugins is reversed to how modules are discovered. And the core plugins get first registered, followed by 3rd part plugins and then inline plugins. When the inline plugin is running there's no virtualenv plugin registered yet, so we can only set to what you're registering. From that point of the view there's no replacement happening here, but whatever you register becomes the default, as is the first one being registered.
