### ISSUE TITLE
pip install always executed when usedevelop=True

### ISSUE THREAD

**Issue by margars** [tox-dev/tox#2336]
Hi,

I am using tox==3.24.5 with the following settings:
skipsdist = True
usedevelop = True

At every execution of tox "pip install -e ." is called even though no file has changed. I assume this is not the expected behavior. My project has setup.py and setup.cfg. Any suggestion?

**Comment by jugmac00** [comment]
Having a look at this test ( https://github.com/tox-dev/tox/blob/47cf25e9085d632f2fb21eab5efdb2012c784595/tests/unit/test_z_cmdline.py#L730-L751 ), I assume this behavior is intentional, ie that `setup.py` is executed, but no packages get re-installed.

Adding your configuration options to one of my projects, I cannot see any `pip install -e.` in my output. Could you please add the complete output of your tox command - do not forget to add `-vv` to increase verbosity.

That all said, `tox4` will be published in the near future, so the tox maintainers allocate their spare time there.

**Comment by margars** [comment]
Thanks for quick reply, the output is attached.

[output.log](https://github.com/tox-dev/tox/files/7985689/output.log)

**Comment by jugmac00** [comment]
I cannot reproduce your problem on Ubuntu 20.04.

This either means the issue is related to your setup or to your os.

Could you try to reproduce the problem with `tox4`?  (`pip install --pre tox`)

**Comment by margars** [comment]
It works as expected with tox4, I will wait for the release. 

Thanks again for quick response.

PS. Some of output text look strange in PowerShell, pytest colors are lost. 
![image](https://user-images.githubusercontent.com/9504931/152172091-a7ec1228-3c01-42d9-a1af-175f7ac9aad7.png)

**Comment by jugmac00** [comment]
Thanks for the feedback. I use `tox4` already for a year or so in production, so no need to wait, unless you encounter a serious problem, but that is up to you.

About the color issue... please report it as a new issue. Unfortunately, I have no access to a windows box, and cannot help with this problem.

**Comment by gaborbernat** [comment]
> PS. Some of output text look strange in PowerShell, pytest colors are lost.

Seems your shell does not handle colouring correctly. Can you provide the exact run environment you're using? I'll probably cut a first beta release today/tomorrow. What we have here will be what we ship soon (minus any bugs reported before it).

**Comment by margars** [comment]
I am using PowerShell 5.1 (running inside ConsoleZ) on Windows 10. In the same environment tox 3.x shows correctly the commands and color. 

![image](https://user-images.githubusercontent.com/9504931/152223989-5f4a0089-aacf-45b6-8510-83fb303f5272.png)

**Comment by gaborbernat** [comment]
Colours might be lost because of https://github.com/tox-dev/tox/issues/1773, for which I don't have a good solution (and the reason it worked for tox 4 is no longer a valid route for tox 3). However, from what your first screenshot shows the colour is printed (hence the [36m chars) but ConzoleZ fails to render it correctly. Can you open a new issue for it please, and mention the powershell + consoleZ combo? Did/can you try it with Windows Terminal and see if that renders it better?

**Comment by margars** [comment]
The problem is still there using default PowerShell window, which suggests it is not related to ConsoleZ.
