### ISSUE TITLE
tox4: error: argument -q/--quiet: ignored explicit argument 're'

### ISSUE THREAD

**Issue by frenzymadness** [tox-dev/tox#2342]
When I try to use the latest tox with merged command-line arguments like `tox4 -qre py310` it gives me the following error:
```
usage: tox4 [--colored {yes,no}] [-v | -q] [-c file] [--workdir dir] [--root dir]
tox4: error: argument -q/--quiet: ignored explicit argument 're'
```
Is that intentional?

**Comment by gaborbernat** [comment]
It's not intentional, will need to dig in deeper to understand why we're getting this 🤔

**Comment by gaborbernat** [comment]
The problem here is explained well in https://bugs.python.org/issue32756

**Comment by gaborbernat** [comment]
And by producing this error you mean it prints that message out on the screen, but otherwise runs successfully.

**Comment by frenzymadness** [comment]
> And by producing this error you mean it prints that message out on the screen, but otherwise runs successfully.

Yes, exactly. I have the latest tox from rewrite branch.

And the mentioned Python bugs seems to be different for me because all arguments here are known and therefore the mentioned paragraph from documentation in the last comment applies here:

> Several short options can be joined together, using only a single - prefix, as long as only the last option (or none of them) requires a value:

https://docs.python.org/3/library/argparse.html#option-value-syntax

**Comment by gaborbernat** [comment]
> And the mentioned Python bugs seems to be different for me because all arguments here are known

This is not true. We have a two-phase CLI argument parsing. The CLI arguments are registered by the plugin system, but before we start running that we need to set up logging based on the content of the `-v` and `-q` (so that logs emitted during CLI argument registration can be correctly displayed). Therefore, right at the start of the application, we register only `-v` and `-q` and use `parse_known_args` to quantify the verbosity level. At this stage `-r` and `-e` is not known, hence the error above. Once the plugin system registered all CLI flags we rerun the CLI argument parsing, so this second will not see the error.

**Comment by frenzymadness** [comment]
Interesting, thanks for the explanation! Not sure how to fix that though.

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/tox/pull/2351/files shows how we can safely ignore if an error is raised in the first part. If the user is interested in the full log they should pass in the arguments separate, e.g. in the above case `tox -q -re py39`. Otherwise, we're safe to ignore the flags for the setup phase. What I missed here was the error written on the stderr so we just need to capture `sys.stderr` during the first phase parsing. We could also probably document in the FAQ that if you want the full log you should specify the `-q` and `-v` on their own and not merge it to other arguments. That's the best I can think of for now.
