### ISSUE TITLE
Use external package builder with --installpkg

### ISSUE THREAD

**Issue by sfc-gh-mkeller** [tox-dev/tox#2442]
Hey,

When using `tox==4.0.0b2` with one of our projects that has an [external package env](https://github.com/snowflakedb/snowflake-sqlalchemy/blob/5d17bfb3dbfb1a9b29d1156c1da538ecf61847e9/tox.ini#L25) it appears as we cannot supply a wheel file through `--installpkg` if we have already built one.

```console
$ tox -rvv -e py39 --installpkg dist/snowflake_sqlalchemy-1.3.4-py2.py3-none-any.whl
ROOT: 330 E HandledError| .pkg_external is already defined as a virtualenv-cmd-builder, cannot be virtualenv-pep-517 too [tox/run.py:21]
```

You can repro the issue with the following commands:

```console
cd /tmp
git clone https://github.com/snowflakedb/snowflake-sqlalchemy
cd snowflake-sqlalchemy
virtualenv -p python3.9 venv
. venv/bin/activate
pip install build
pip install --pre tox
python -m build -w -o dist
tox -rvv -e py39 --installpkg dist/snowflake_sqlalchemy-1.3.4-py2.py3-none-any.whl
```

Thanks for the help!

**Comment by sfc-gh-aling** [comment]
hey, I work with Mark on the snowflake-sqlalchemy project and love to share more details as I were debugging this issue:

- the tox will loops the envs list defined in `tox.ini` and build pkg envs
- when it encounters the env `py39` , it found `installpkg` option is set and will then build a `VirtualEnvCmdBuilder`  for the env `.pkg_external`
- when it encounters the env `fix_lint`, because we set `skip_install` to true in the `fix_lint`, the tox build a `Pep517VirtualEnvPackager` for the env `.pkg_external`
- whichever env (`py39` or `fix_lint`) is built first, the second one would conflict the first one on existing `.pkg_external` env as defined in the code:
https://github.com/tox-dev/tox/blob/4.0.0b2/src/tox/session/env_select.py#L264-L267

I'm not very familiar with how `.pkg_external` module is designed, but just looking at the issue, my gut feeling is that it might be better if each env has its own `.pkg_external` env or ignore the following attempts to build `.pkg_external` is there's already one.

**Comment by sgbaird** [comment]
Installing tox via GitHub actions suddenly stopped working (no changes between commits of the repo: first scheduled test ran fine, next scheduled test resulted in:
```python

**Comment by gaborbernat** [comment]
@sgbaird PR to fix this is welcome 👍

**Comment by sgbaird** [comment]
@gaborbernat I'll see if I can figure out where the discrepancy is. Any thoughts on pinning the tox version so I can verify a release that is working?

I get the following error which @ssbarnea also mentioned https://github.com/tox-dev/tox/issues/2409#issuecomment-1116999358:
```python
Run pipx run tox --installpkg 'dist/self_driving_lab_demo-0.6.0.post1.dev87+g694e3a0-py3-none-any.whl' -- -rFEx --durations 10 --color yes
creating virtual environment...
installing tox...
ROOT: will run in automatically provisioned tox, host /opt/pipx/.cache/5d372be6c729ea1/bin/python is missing [requires (has)]: tox<4.0.0 (4.0.5)
```
https://github.com/tox-dev/tox/issues/2414 is also mentioned, though obviously the error is still cropping up.

**Comment by gaborbernat** [comment]
This is likely a version 4 bug, any version 3 should work.

**Comment by sgbaird** [comment]
@gaborbernat ah gotcha, I was thinking it had worked in `v4` since I had a successful run on 2022-12-07, but I'm realizing what probably happened is the first version installed a `v3` (I'm guessing the `rc` versions, e.g. `v4.0.0rc4` won't get installed unless specifically requested) and the next version installed one of the other 2022-12-07 tox releases.

**Comment by webknjaz** [comment]
I've also encountered this issue. I noticed in one of the backlinked PRs @freakboy3742 suggests that a workaround could be `package_env = none` — https://github.com/beeware/briefcase/pull/995/files#r1042849461.
Though, I'm not sure what the side effects of this would be, so I'm just linking it for visibility.

**Comment by webknjaz** [comment]
In that issue, @freakboy3742 claims that the incompatibility is related to using the `extras` setting in `tox.ini` but in my case, I don't have it and I still face this problem. I don't have a `.pkg_external` env defined either.

**Comment by freakboy3742** [comment]
FWIW: my investigation didn't suggest it was *exclusively* about extras; it's about having multiple targets in a toxfile, with 2 different install schemes. I'm using `--install_pkg` on one target, and `skip_install` on another. This seems to cause Tox confusion because the target being installed from a wheel uses a PEP517 environment, and the `skip_install` tries to use an old-style install environment (even though, by definition, nothing is being installed); the inconsistency between the two installation approaches is what raises the error.

Adding `package_env = ` with *any* value on all `skip_install` targets is enough to avoid the problem. This seems to be enough to convince tox that there's no incompatibility between the skip_install and installed environments because the `skip_install` targets will use an isolated install environment. The dummy `package_env` is never created - because nothing is installed - but the validation step passes.

**Comment by webknjaz** [comment]
@freakboy3742 thanks for the clarification!

# :point_right: CURRENT WORKAROUND FOR PEOPLE COMING FROM GOOGLE :point_left:

I have verified that setting `package_env = ❌ DUMMY NON-EXISTENT ENV NAME ❌` in _**every** toxenv_ that has `skip_install = true` works (yes, I tried it out with emojis :hear_no_evil:, so it raises a red flag if it ever starts to be used by tox).

**Comment by takluyver** [comment]
If you have CI running on Windows, you may need to get rid of the emoji in the above workaround.

On Azure pipelines, all my jobs started failing, with a warning message saying:

```
ROOT: No tox.ini or setup.cfg or pyproject.toml found, assuming empty tox.ini at D:\a\1\s
```

This is because file I/O has the unfortunate default of using a platform-dependent encoding, so it doesn't read files as UTF-8 by default on Windows. Then, because unicode errors subclass from ValueError, the exception is swallowed by [this code](https://github.com/tox-dev/tox/blob/d8e86ddfa44e02470aa239789b448fd0211d430e/src/tox/config/source/discover.py#L50-L53) which is meant to catch missing files.

It took me a while to realise this, even though I'm quite familiar with encoding errors, so I hope this saves someone else some time.

**Comment by webknjaz** [comment]
> If you have CI running on Windows, you may need to get rid of the emoji in the above workaround.

I was facing tracebacks in my case :) Ended up using `sed -i` to "rename" it under Python 3.6 and Windows. For the newer Pythons, I was able to solve this with the env vars.

**Comment by q0w** [comment]
Does it really need to check twice if it has external_pkg. In `self._register_package_conf()` it already  set package=external if `--install-pkg` is used. This patch seems fix the problem above

```diff
--- a/src/tox/tox_env/runner.py
+++ b/src/tox/tox_env/runner.py
@@ -87,9 +87,8 @@ class RunToxEnv(ToxEnv, ABC):
         self._call_pkg_envs("interrupt")
 
     def get_package_env_types(self) -> tuple[str, str] | None:
-        has_external_pkg = getattr(self.options, "install_pkg", None) is not None
-        if self._register_package_conf() or has_external_pkg:
-            has_external_pkg = has_external_pkg or self.conf["package"] == "external"
+        if self._register_package_conf():
+            has_external_pkg = self.conf["package"] == "external"
             self.core.add_config(
                 keys=["package_env", "isolated_build_env"],
                 of_type=str,
```

**Comment by gaborbernat** [comment]
I don't think 🤔 it does to check twice.
