### ISSUE TITLE
--workdir override not working in tox >=4

### ISSUE THREAD

**Issue by jabbera** [tox-dev/tox#2654]
## Issue

In tox <4 using --workdir would override whatever was in tox.ini, this no longer works in >= 4 which makes some CI/CD use cases difficult 

## Environment

Provide at least:

- OS: linux

## Minimal example

If possible, provide a minimal reproducer for the issue:

```
tox.ini:
[tox]
toxworkdir=/tmp/blah

[testenv]
allowlist_externals=echo
commands=echo {toxworkdir}

setup.py
from distutils.core import setup

setup(name='Distutilsaaa',
      version='1.0',
      description='Python Distribution Utilities',
      author='Greg Ward',
      author_email='gward@python.net',
      url='https://www.python.org/sigs/distutils-sig/',
      packages=['distutilsa'],
     )

distutilsa/__init.py

```

Tox 4:
```
 jabbera    toxbug   3.8.10  ﮫ20.419s⠀   tox -e py --workdir /tmp/blah1  70  19:30:47 
.pkg: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel
.pkg: _optional_hooks> python /home/jabbera/.local/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /home/jabbera/.local/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /home/jabbera/.local/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /home/jabbera/.local/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py: install_package> python -I -m pip install --force-reinstall --no-deps /tmp/blah/.tmp/package/1/Distutilsaaa-1.0.tar.gz
py: commands[0]> echo /tmp/blah
/tmp/blah
.pkg: _exit> python /home/jabbera/.local/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  py: OK (6.34=setup[6.34]+cmd[0.00] seconds)
  congratulations :) (6.43 seconds)
```

Tox 3:
```
 jabbera    toxbug   3.8.10  ﮫ4.404s⠀   tox -e py --workdir /tmp/blah1         bash   70  19:29:36 
GLOB sdist-make: /home/jabbera/toxbug/setup.py
py inst-nodeps: /tmp/blah1/.tmp/package/1/Distutilsaaa-1.0.zip
py installed: Distutilsaaa @ file:///tmp/blah1/.tmp/package/1/Distutilsaaa-1.0.zip
py run-test-pre: PYTHONHASHSEED='1612454640'
py run-test: commands[0] | echo /tmp/blah1
/tmp/blah1
_______________________________________________________ summary ________________________________________________________
  py: commands succeeded
  congratulations :)
```

**Comment by gaborbernat** [comment]
Minimal reproducible:

```ini
[tox]
toxworkdir=/tmp/blah
```

```bash
❯ tox c -k toxworkdir --core -e py --workdir a
[testenv:py]

[tox]
work_dir = /tmp/blah
```

PR welcome with test and changelog.

**Comment by jabbera** [comment]
I tried to fix this but there doesn't seem to be an obvious way to differentiate if a parameter is passed or the default is called. That said: -x tox.toxworkdir=blah sorts the problem.

**Comment by jaraco** [comment]
I'm continuing the analysis from #2713.

**Comment by jaraco** [comment]
In #2725, I have a few commits that start to address this issue, but there are still a few test failures. Annoyingly, I can't even seem to get consistent test failures. A moment ago, `test_sequential_inserted_env_vars` was failing due to a failed assertion on test_sequential:435, but now it's failing on :437. When it was failing on 435, it was failing because the virtualenv couldn't find `pip`... so maybe there was some issues with cached envs in the tree. It does appear that if `--root` is passed, the [expectation](https://github.com/tox-dev/tox/blob/20ab8a00d19a4bae2d05112e3306880119f78477/tests/session/cmd/test_sequential.py#L426-L442) is that the work_dir should still be relative to the project directory and not the root ([gist](https://gist.github.com/f14cd5807411e1542832264a9966a761)).

It seems to me it's ill-defined what the value of `work_dir` is expected to be when `root_dir` is specified, `work_dir` is unspecified, and `source.path.parent` is not `root_dir`, and the tests make a lot of assumptions about `work_dir` being `{source.path.parent}/.tox`.

The docs talk about a tox root and a package root. `--root` points to where the project root is. Is the `work_dir` meant to be relative to the tox root or the project root or package root? Is project root the package root or tox root?

**Comment by gaborbernat** [comment]
> Is the `work_dir` meant to be relative to the tox root or the project root or package root? 

Relative to `tox_root` when not specified, otherwise the path where it's specified.

> Is project root the package root or tox root?

Project root should default to `tox_root`, but can be changed.

Package root defaults to `tox_root`, but can be changed.

**Comment by jaraco** [comment]
What is the difference between package root and project root? How is package root defined? Do I understand correctly that tox_root is always where the ini file is found? How can package root be changed?

**Comment by gaborbernat** [comment]
> How can package root be changed?

Always relative to the project root, it can be changed via the tox.ini config.

> Do I understand correctly that tox_root is always where the ini file is found?

Yes.

> What is the difference between package root and project root? How is package root defined?

By default is package root is the project root, but can be changed via tox.ini.

**Comment by jaraco** [comment]
What I mean to ask: what is the purpose of package root and project root compared to each other? What value would someone get by defining them separately?

**Comment by gaborbernat** [comment]
Packaging root is used by the package builder as the root directory. Project root is what tox uses as root directory.

**Comment by q0w** [comment]
@gaborbernat 
The problem is here https://github.com/tox-dev/tox/blob/a36ff9dcf9457a56cf8e694b6dce40ac79566242/src/tox/config/of_type.py#L96-L110
the last else block is never called, and tox gets the `toxworkdir` from `IniLoader` and `work_dir_builder` as default is never called, so not from cli args
