### ISSUE TITLE
After successful completion of the tox, it gives "congratulations :)" string. It must give exact end users understandable smileys i.e. "Congratulation ☺"

### ISSUE THREAD

**Issue by raiesmh08** [tox-dev/tox#442]
After successful completion of the tox, it gives "congratulations :)" string. It must give exact end users understandable smileys i.e. "Congratulation ☺"

**Comment by obestwalter** [comment]
Hi @raiesmh08 thanks for your suggestion and PR. Let me just give you a bit of feedback about this:

1. (Just a minor nitpick): "congratulations" (plural) is more commonly used than the singular, so I would not change that (e.g. see http://english.stackexchange.com/a/5973/95411).
2. Although the tests are passing now, I have a very bad feeling about using unicode simply due to a lot of horrific unicode related experiences in Windows consoles. See for example this package that also gives information about a few problems one can face: https://pypi.python.org/pypi/win_unicode_console or this [SO question](http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how/388500#388500)

So although this looks like a nice idea, I would not change this just because the gain in aesthetic pleasure might be outweighed by the problems we might cause for a lot of Windows users.

**Comment by hpk42** [comment]
agree with @obestwalter: maintainers are too anxious about adding unicode to output.

**Comment by warsaw** [comment]
Yes, there are plenty of environments where unicode may be problematic.  See the intense discussions around PEP 538 and 540.

**Comment by warsaw** [comment]
The real question is whether the smiley has glasses or a nose.  E.g. if you use nose or nose2, then it should be :-)  but if you need glasses, it should be 8-).  So many possibilities!

(^^ is a joke and notice the asciimoji i used there?

**Comment by raiesmh08** [comment]
hehehehe.. Very nice. My suggestion is turned into fun :+1:
