### ISSUE TITLE
No clear way to donate to the project

### ISSUE THREAD

**Issue by posita** [tox-dev/tox#485]
Nit: While there is an option for [paid professional support](http://tox.readthedocs.io/en/latest/support.html#paid-professional-support), there is no clear way to donate to the project through some other means. It would be nice to know how if this is an option and how to exercise it if it is.

**Comment by obestwalter** [comment]
Hi @posita,

well first thank you that you want to support the project, or at least want to know how :)

Additionally to the main channel of support (donating your time and expertise) there is the possibility to fund the next upcoming sprint, which is likely going to happen again this year and will likely be funded in a similar way. See [last years Indiegogo campain](https://www.indiegogo.com/projects/python-testing-sprint-mid-2016#/) for details. AFAIK there is nothing set up yet for this year though, but I'll update this issue as soon as I hear something.

Last but not least for direct consulting or scheduling pytest/tox trainings you can contact the mail address mentioned in the link you referred to, to get more info directly from Holger.

Do you have tips or suggestions from your own experience how to establish an easy and clear way of supporting an OSS project financially?

**Comment by posita** [comment]
> Do you have tips or suggestions from your own experience how to establish an easy and clear way of supporting an OSS project financially?

I've never been on the collecting side, so I can't adequately address that. I hear that various governments (perversely) make it increasingly onerous for people to give/receive monetary gifts, so it may not be worth the trouble?

That being said, I've noticed the mechanisms vary. In small cases, I've seen "tip jars" (via PayPal, Amazon, etc.). In large ones, a foundation is created (often a 503-c non-profit in the United States) that either accepts charitable gifts, applies for grants, etc. under a general charter or under a specific project. Sometimes one will receive a grant from the other (see, e.g., [Mozilla partially funding PyPy 3.5 development](http://pypy.org/py3donate.html)).

**Comment by obestwalter** [comment]
Beside from the direct financial aspect, wich I am not watching too closely myself, another important avenue is to get the companies on board that profit from the use of OSS. As a company relying on OSS you have to give your developers, technical writers, designers, marketing people, etc. time and space to be a part of the community. That's not a nice to have that is the only way this model will be sustainable in the long run.

To talk about myself: Since the beginning of this year [Avira](https://avira.com)  ❤️ grants 20% of my working time for my work on OSS. For me this is a great opportunity to learn more about how this OSS thing works, once you get deeper involved than just opening issues and shooting the occasional PR and for my company it is an opportunity to give back in a different way than just throwing money at something, so everybody wins 😺.

**Comment by posita** [comment]
That's great. I've been fortunate enough to work for employers who understand the value of supporting OSS projects, especially those from which those employers directly benefit. One good way that involves very little additional effort is to take the time to create public PRs with any patches needed in the proprietary context to fix bugs in the OSS project. Heck, even just filing a worthwhile issue capturing the bug is a worthwhile contribution. Sadly, I'm guessing that actually happens _maybe_ one in a couple dozen times.

**Comment by obestwalter** [comment]
Another thing I forgot, which is in the works is to participate in Google Summer of Code. If this happens there will be some money going to the project as well: https://github.com/pytest-dev/pytest/wiki/GSoC-2017

**Comment by obestwalter** [comment]
Closing this as clarified. If someone wants to contribute and organize a way to donate to the project they can open a new issue discussing how to go about that.
