### ISSUE TITLE
Look into environment variable passing

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#539]
Since the change from passing everything to passing almost nothing in tox 2.0 a number of problems popped up. Since then the list of variables that are passed by default is growing again.There might be still be bugs due to this that are not easy to recognize for the average user, so it might be worth to look into it a bit closer instead of waiting for issues to be opened. 

This is more of a research task for needles in a haystack and needs to be done for Windows, macOS and Linux, but if someone is into this kind of research help would be very appreciated.

**Comment by The-Compiler** [comment]
I think it's actually quite hard to find a good default for this, and it might make sense to think about a policy for what the default should be first - maybe something like "we pass through everything needed by the Python standard library and pip/setuptools to work by default".

I personally don't like anything to be passed through by default, but I can see that other people might see this differently. Why? Because I want to know what parts of the environment my code relies on, and I want that to be enforced and "documented" :wink:

I do `passenv =` in many environments. For my tests I currently do `passenv = PYTHON DISPLAY XAUTHORITY HOME USERNAME USER CI TRAVIS XDG_* QUTE_* DOCKER` but I probably should look into reducing that set more.

**Comment by obestwalter** [comment]
Hi @The-Compiler from what I see, most of the problems are on macOS and Windows due to hidden dependencies where functionality from stdlib breaks if an env var is not present - e.g. https://github.com/tox-dev/tox/issues/517 - so these are things where we have to consider this a bug if it is not passed through automatically.

But I agree - maybe it is better to discuss first what the RightThing is here ...

**Comment by AndreLouisCaron** [comment]
@The-Compiler I totally agree with you.  I prefer not to pass things by default.  This indeed helps document what the dependencies are.

> we pass through everything needed by the Python standard library and pip/setuptools to work by default"

IMO, this seems like a good starting point.  Maybe we should have a section in the docs that list which ones Tox forwards by default (with rationale)?

**Comment by obestwalter** [comment]
> Maybe we should have a section in the docs that list which ones Tox forwards by default (with rationale)?

Already there: http://tox.readthedocs.io/en/latest/config.html?highlight=passenv#confval-passenv=SPACE-SEPARATED-GLOBNAMES

But thanks for mentioning this, because I am not sure if the last PRs adding more variables updated the docs.

**Comment by AndreLouisCaron** [comment]
I definitely dit not think of adding those to the docs in the last PRs I submitted.  Sorry!

**Comment by obestwalter** [comment]
tracking in https://github.com/tox-dev/tox/issues/542 to make sure this lands in 2.8

**Comment by obestwalter** [comment]
I think we just have to take this as it comes. Slowly we should have re added everything that is necessary already (he sad full of hope).
