### ISSUE TITLE
tox-quickstart points to wrong config ref url

### ISSUE THREAD

**Issue by auria** [tox-dev/tox#543]
Here's the tox-quickstart output (Ubuntu Xenial): http://pastebin.ubuntu.com/25009894/

Last config reference url points to:
http://tox.testrun.org/latest/config.html

which redirects to (404):
https://tox.readthedocs.io/latest/config.html

instead of (200 OK):
https://tox.readthedocs.io/en/latest/config.html

general.useragent.locale is en-US. I think redirect should default to "en" if unable to guess the language.

**Comment by obestwalter** [comment]
Hi @auria this is fixed since 2.7: https://github.com/tox-dev/tox/commit/b270bb786ddb6ea55cf41270912bd215e637c0f0 

Please update your tox installation.

If you use Linux with an old packaged tox:
* packaged tox on Linux is often pretty old, use pip to install newer versions
* you do not have to install tox into the system - you can also install tox into a virtualenv and run it from there.

**Comment by obestwalter** [comment]
About the redirect: this would be the better solution to have a proper redirect from the old url, but nobody got around to doing this, I guess ...
