### ISSUE TITLE
style guide and checker

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#558]
Looking through the project sometimes feels like random styles mixed together, maybe we should have an official style guide - and have some kind of checker for it - flake/pylint and so on 👍

**Comment by obestwalter** [comment]
Hi @gaborbernat, I know ... my PyCharm with all style warnings on is also very unhappy when opening the code. If you want to carrefully make the code more PEP8 conform, I for one would appreciate this. This should be done in small increments though while making absolutely sure that no accidental behavioural changes are introduced. I have to admit that I got myself into trouble more than once by making big sweeping style changes that introduced a change in behaviour, because I was not careful enough :) 

I usually have flake8 in my projects with all warnings active and the standard line lenght of 79. I am quite happy coding within those restrictions. Regarding naming variables I have a slightly different taste (I prefer camel case names for things that behave like data and slug case for things that behave like functions, which is not very widespread and I only use it in my own projects), but besides from that, I am o.k. with full on flake8 (including the cyclomatic complexity restriction to keep functions from growing into behemoths).

Current state for tox is that pep8 and flakes is run already: https://github.com/tox-dev/tox/blob/2.7.0/tox.ini#L55 - some things are deactivated. If these tests pass, I consider the code stylistically "good enough" amd won't insist in people fxing it in their PRs. I rather fix it myself after merging, if I deem it necessary and have the time/mind space.

I also met the https://coala.io guys at EuroPython and they have done some nice things to improve static code analysis and also tooling around dealing with Github issues (https://app.gitmate.io/#/) - so maybe you want to have a look at these, to see how we could use those tools to improve the health of tox?

**Comment by gaborbernat** [comment]
@obestwalter I also use PyCharm. But yeah, I'm bothered enough to be willing investing time on this :+1:

**Comment by obestwalter** [comment]
@gaborbernat there is really nothing modern about any line length. 79 is just as modern (and arbitrary) as 120. I prefer shorter line length nowadays, after just using the 79 proposed in PEP8 for all my projects and I actually see the value of it now.

At the moment tox has `pep8maxlinelength = 99` set and I guess we can just stick with that, as it was established @hpk42 and we don't have to fight over line lengh :)

**Comment by gaborbernat** [comment]
I meant modern meaning by not trying to adapt to low resolution screens so popular 20 years ago, but more towards the modern-ish Ultra-HD screens. But okay, let it be 99,  I'm not going to start a war out of this.

**Comment by obestwalter** [comment]
O.k. then lets stick with that - war over line length successfully avoided :)


BTW: I know what you mean by modern. I was just challenging that view. Just because we have wide screens now does not mean the lines should be longer. We can also fill the extra space with lots of PyCharm tool windows, etc. :)

**Comment by gaborbernat** [comment]
yeah I know; I don't like to show almost any tool windows cause I think it just takes away focus from the content - I believe those tools windows should be on demand auto hidden; but that's a style preference so whatever 👍

**Comment by gaborbernat** [comment]
fixed via https://github.com/tox-dev/tox/pull/581
