### ISSUE TITLE
Tox does not use downgraded wheel for older python releases

### ISSUE THREAD

**Issue by brovercleveland** [tox-dev/tox#648]
Bug is detailed here:
https://stackoverflow.com/questions/46614281/installing-pandas-with-tox-for-py26

When using tox 2.9.1 with a py26 env, wheel 0.30.0 is used to install dependencies, which is no longer compatible with py26.  Specifying `wheel==0.29.0` in `deps` does not affect the wheel version used to install subsequent packages.  Are there additional config options that can be used to specify a particular wheel version, or does this feature not yet exist?

Running tox 2.9.1, OS X 10.12.6.  Global python version: 3.6.2, bug appears with local python 2.6.9

**Comment by obestwalter** [comment]
Hi @brovercleveland - thanks for the report - it [has been answered already](https://stackoverflow.com/a/46614575/2626627) - wheel dropped Python 2.6 support. This is actually happening on a widespread number of tools, as pip is about to drop support and a lot of tools will be dropping support soonish. tox and pytest will do that also. So, the real solution is to upgrade to 2.7 as soon as possible and then you have a few more years on legacy Python, looking at the vast amount of Python 2.x behind corporate firewalls, I would reckon even decades :)

BTW: the actual error is because the wheel uses a set literal in that lambda which does not exist in Python 2.6.
