### ISSUE TITLE
Run appveyor builds under a tox-dev organization

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#750]
At the moment appveyor builds are managed under the account of @gaborbernat.

I'd propose that this should be moved into an "tox-dev" org account and team members should all have admin access (don't know how this is actually called in appveyor). If team members want to move their appveyor builds into the org they should be able to do so.

**Comment by asottile** [comment]
fwiw I looked into doing something like this when I was added to the sass org for https://github.com/sass/libsass-python

It turns out it's not very simple to get working.  The unfortunate bits being that you can't use github login, need to set up a passworded account, and then somehow need to share that password.  So I just stuck with my user account (and it seems most repositories I've looked at do this).

**Comment by obestwalter** [comment]
Hi @asottile ... ah o.k. - well if nothing else comes up we might just have to live with it like it is until either appveyor gets their act together or some other windows CI platform provides org friendlier workflows.

**Comment by gaborbernat** [comment]
not needed anymore as we have azure pipelines
