### ISSUE TITLE
Allow specifying pip version

### ISSUE THREAD

**Issue by OrangeDog** [tox-dev/tox#791]
Currently it appears tox always installs the latest pip when (re)creating virtualenvs.
However sometimes ([like today](https://github.com/pypa/pip/issues/5251)) the latest version doesn't work, or you haven't yet accounted for breaking changes.

Tox should have a way to control the version of pip.
Perhaps a `pip_version` config property, or allowing `install_command` to be multiple lines.

**Comment by asottile** [comment]
The _latest_ behaviour here is due to `virtualenv`'s downloading behaviour.  If you want a more "consistent" version, I might suggest using [tox-virtualenv-no-download#wait-why](https://github.com/asottile/tox-virtualenv-no-download#wait-why).

Related: #448

**Comment by gpotter2** [comment]
> The latest behaviour here is due to virtualenv's downloading behaviour.

Is that still accurate ? Since today (new release?!), [some of our AppVeyor builds](https://ci.appveyor.com/project/secdev/scapy/build/job/c55pa1xh76kerm98) (Python 2.7 builds) fail with an outdated `pip` version.

I bumped into https://github.com/tox-dev/tox/issues/765 then here :/

**Comment by gaborbernat** [comment]
soon you can override the default version into pip, in the meantime please upgrade virtualenv alongside tox to get later defaults.👌

**Comment by gaborbernat** [comment]
And yes with the latest version we no longer download latest pip.

**Comment by gaborbernat** [comment]
When installing tox use the force reinstall flag to get latest virtualenv 😀

**Comment by gpotter2** [comment]
Thanks for this light-speed answer :smile:

**Comment by gpotter2** [comment]
Does tox uses the pip version of the virtualenv ?
I'd rather update only pip

**Comment by gaborbernat** [comment]
tox creates virtual environments that have their seed packages (pip, setuptools, wheel) with the version bundled within the virtualenv installed alongside it. you can of course use the deps then to upgrade to install another version. Or just upgrade virtualenv to have newer bundles.

**Comment by jayvdb** [comment]
There is https://github.com/pglass/tox-pip-version which does what this issue requests, I believe

**Comment by pglass** [comment]
> you can of course use the deps then to upgrade to install another version

@gaborbernat This doesn't actually work in my experience. It will install a version of pip, yes, but tox will not actually use that new version of pip to install the rest of the dependencies. 

The reason is because tox runs _one_ pip command to install everything, like `python -m pip install pip==19.1 requests` (see example below). It won't start using pip version 19.1 until the _next_ pip command is run.

```ini
[testenv]
deps =
    pip==19.1
    requests
```

Some other things I've tried:

- Trying to change the install command, like `install_command = pip install -U 'pip==18.1' {opts} {packages}` has the same issue. 
- Using [tox-run-before plugin](https://github.com/praekelt/tox-run-before), but this runs commands prior to the creation of the tox virtualenv (so it affects the currently active non-tox venv or else your system-wide installation, which is yucky), which brings me to the next point...

It is true that if you install a specific version of `virtualenv` prior to running tox, you can change the effective version of pip that tox uses to install packages. But, this still falls short in some ways:

- This is not a solution for users of `tox-venv`, which uses `python -m venv` instead of the virtualenv package
- It's not obvious which version of the virtualenv package comes with a particular version of pip (poor user experience)
- Releases of the virtualenv package lag behind releases of pip (from a day to up to a week), so this isn't a viable solution in the "critical" period when a new release of pip breaks you

Hence, I did make a plugin for this (see previous comment), but it would be much nicer for this to be a native feature.

**Comment by gaborbernat** [comment]
This will be fixed on the virtualenv side, I'm actively working on https://github.com/pypa/virtualenv/issues/1366, I hope to have something by the end of the month.

**Comment by ssbarnea** [comment]
Any update on that? I am looking for a workaround that can be used today, without waiting for a newer version of virtualenv.

**Comment by asottile** [comment]
@ssbarnea do you want "latest" -- you can re-enable virtualenv's downloading by setting the testenv `download` option:

```ini
[testenv]
download = true
```

**Comment by gaborbernat** [comment]
No direct progress on this. Made some progress on the tox rewrite that will allow me to test the virtualenv rewrite... Coming along but this is a major effort (fixing a lot of hard issues while at it - e.g. lazy configuration load), so probably will last into September.

**Comment by The-Compiler** [comment]
FWIW I'm using [tox-venv](https://github.com/tox-dev/tox-venv) because I've had some trouble with virtualenv in the past. This means I get whatever pip which ships with Python's ensurepip ([as of Python 3.8.1](https://github.com/python/cpython/blame/v3.8.1/Lib/ensurepip/__init__.py#L13), that's pip 19.2.3). However, I needed to install manylinux2014 wheels, which requires pip 19.3...

Installing [tox-pip-version](https://github.com/pglass/tox-pip-version) and setting `pip_version = pip` in `[testenv]` to get the latest pip worked beautifully - thanks @pglass! :tada:

**Comment by gaborbernat** [comment]
tox-venv will become obsolete once https://github.com/pypa/virtualenv/pull/1481 lands, and that will also solve this issue on virtualenv side 👍

**Comment by The-Compiler** [comment]
I've been hearing about virtualenv rewrites for the past five years or so, so I wonder how this one turns out - good luck! :crossed_fingers:

**Comment by gaborbernat** [comment]
This one is very close to ship-able, 😊 so will actually happen, latest end of February!

**Comment by Kentzo** [comment]
Updating virtualenv that is installed alongside tox may not be an option since it may not support target python.

E.g. my host Python is 3.7 and my target Python is 2.6 / 3.4. Therefore I can install the most recent tox, but I cannot install the most recent virtualenv with most recent virtualenv dependencies.

**Comment by gaborbernat** [comment]
Hello @Kentzo sadly we no longer support Python2.6, even at the target level. Python3.4 should still work.

**Comment by Kentzo** [comment]
I just hope that this issue will not resurface in the future. Tox's dependency on virtualenv_support is a major PITA.

**Comment by gaborbernat** [comment]
Not sure what alternatives you're proposing here 🤷‍♂

**Comment by Kentzo** [comment]
Ability to update pip / setuptools / etc inside bootstrapped virtualenv before installing any of the deps. Perhaps an ability to execute arbitrary shell code.

**Comment by gaborbernat** [comment]
Definitely no to arbitrary shellcode; ability to do those via virtualenv will be provided; to be fair it already is via the --download flag of virtualenv.

**Comment by gaborbernat** [comment]
This should be now possible by setting ``VIRTUALENV_PIP=19.0.0``.

**Comment by rouge8** [comment]
> This should be now possible by setting `VIRTUALENV_PIP=19.0.0` with virtualenv 20.

@gaborbernat is there a way to tell tox what version of virtualenv to use? Or do we have to make sure people are running virtualenv 20+ another way?

**Comment by gaborbernat** [comment]
You can use the requires key in the configuration.https://tox.readthedocs.io/en/latest/config.html#conf-requires
