### ISSUE TITLE
option to skip a factor level

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#824]
For example if ``{py27,py36}-{nocov,cov,diffcov}``. @warsaw

In this case the user might want to not run all non diffcov envs.

**Comment by warsaw** [comment]
A little more detail.  In an example such as above, we generally run all the factors, however if we create an sdist, then unpack it and run `tox` in the unpacked directory, all `-diffcov` environments will fail.  This is because diffcov only runs in a git repo (because it does diff comparisons against master).  So when running in a non-git repository (e.g. an unpacked sdist), we want to skip all the diffcov environments.

**Comment by gaborbernat** [comment]
@obestwalter @asottile @warsaw 

Here's what I propose, what if the users could do fnmatch filtering in env specification?

**Comment by rpkilby** [comment]
This would conflict with passing a list of test env names (eg, `tox -e isort,lint`)

**Comment by gaborbernat** [comment]
maybe have a separate env var for it then?

**Comment by rpkilby** [comment]
Maybe `-re`?

**Comment by gaborbernat** [comment]
I would be even fine with having just an environment variable (``TOX_ENV_FILTER``). This is an advanced feature for advanced users I would believe.

**Comment by warsaw** [comment]
@gaborbernat I think that would be good enough for me.
