### ISSUE TITLE
[BUG] Tox not respecting data_files in setup.py

### ISSUE THREAD

**Issue by kira0204** [tox-dev/tox#844]
Hi,
I am trying to build a project on travis and using tox for testing https://travis-ci.org/kira0204/thug/jobs/390900758, but tox is not copying the config files in the location specified in the `data_files` in setup.py
https://github.com/kira0204/thug/blob/b1f30a8bb57a8af1ccb8b37f8da6d10a706ade69/setup.py#L58-L83

I would be opening the same issue on [pypa/setuptools](https://github.com/pypa/setuptools) cause there is a good chance that the problem is on that side.

cc @buffer
Thanks

**Comment by asottile** [comment]
The failure on travis-ci is a failure to build pyv8 -- is this the error you're referring to?

`tox` doesn't really do much special with respect to setuptools -- you can replicate ~roughly how it does an installation:

```bash
rm -rf dist
python setup.py sdist
virtualenv venv
venv/bin/pip install dist/*.tar.gz
```

(I'm able to do this successfully with `--no-deps` on the last step since I too don't have the headers to properly build `pyv8`)

**Comment by gaborbernat** [comment]
@kira0204 are you talking about https://github.com/pypa/setuptools/issues/1387? I think this is definitely a setuptools issue. Tox just invokes ``python setup.py sdist`` and then feeds that to ``pip``. We don't do the packaging itself though.

**Comment by kira0204** [comment]
@gaborbenat Yeah, thanks for telling how tox installs the package.
