### ISSUE TITLE
Duplicate release mails

### ISSUE THREAD

**Issue by The-Compiler** [tox-dev/tox#895]
I got 29 mails (from `toxdevorg@gmail.com`) telling me that tox 3.1.1 was released today, each of them having another tox-dev mailinglist footer. Is this some misconfiguration in the mailinglist, or some kind of script going haywire?

**Comment by gaborbernat** [comment]
Hello @The-Compiler. True we have switched over to an automated release notification system, so now a script is running for this. That being said we only sent out two e-mail and our role accounts sent box confirms this. The first did not go out because the role account wasn't subscribed yet to the mailing list and as such required administrator approval. Maybe it's an issue with the mailing list where every approval sent it out?

![screenshot-mail google com-2018 07 10-11-31-34](https://user-images.githubusercontent.com/690238/42504891-04b8b9cc-8435-11e8-8492-d156ba4db283.png)

**Comment by obestwalter** [comment]
I manually confirmed the two automated release mails (3.1.0 and 3.1.1) in and only received them once. So I have no idea where these copies come from.

**Comment by nicoddemus** [comment]
I only received two emails as well.

**Comment by obestwalter** [comment]
Hi @The-Compiler, weird though. Did the original mail got sucked into some kind of duplicating worm-hole?

**Comment by The-Compiler** [comment]
I've talked to postmaster@python.org, and apparently, tox-dev@python.org is subscribed to tox-dev@python.org :laughing:. I contacted tox-dev-owner@python.org hoping that they can fix this.

**Comment by obestwalter** [comment]
oh ... that'll be me, I guess. I wonder if I accidentally added that. I had to wave the release mails through, because they needed approval (sender was not subscribed yet). Sorry for the noise and thank you so much for sorting it out.
