### ISSUE TITLE
Add verbosity option to be piped through during `pip install` of sdist

### ISSUE THREAD

**Issue by ericvw** [tox-dev/tox#982]
The scenario in which I am using `tox` is running tests on a C-extension across multiple interpreters with different build-level optimizations.  For example:

```
[tox]
envlist = {py27,py36,py37}-{dbg,opt}

[testenv]
setenv =
    dbg: CFLAGS=-O0
    opt: CFLAGS=-O3
deps =
    cython
    pytest
commands = pytest
```

When invoking `tox -vv` or inspecting the various logs produced, I was unable to easily determine whether the `CFLAGS` were being passed through during the `pip install` of the sdist.

`tox --showconfig` does illustrate that it is observing the setting desired, but it would also be desirable to also observe the flag set during the build of the package.

I would like to propose:

1. Have`-v` or `-vv` pass through `-v` or `-vv` to `pip`, respectively. 
2. Expose a separate option for controlling the verbosity of `pip` during `pip install` of the sdist.
3. Or some other mechanism for passing verbosity down to `pip`.

As I was just writing this, I tested that `PIP_VERBOSE=1 tox -v` also achieves the desired result.  Given that, I would equally be OK if it was decided to not thread-through the verbosity to the underlying `pip install`.  However, it would be conveniently useful :).

**Comment by gaborbernat** [comment]
In general we're wary of adding new flags because some of the tools are tool dependent and e.g. they may be replaced by other tools that don't have that flag. That being said pip is already handled specially so this is ok. I propose adding the following flags.

One v, tox info.
two v, tox debug messages.
three v, dependent tools single v.
four v, dependent tools two v.

This way the tool verbosity kicks in later but stil reachable without knowing arcane environment variable flags. Will implement with 3.4.
